SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE SCHEMA IF NOT EXISTS tasks;

SET default_tablespace = '';

CREATE TABLE tasks.tasks (
    id bigint NOT NULL,
    closing_date timestamp without time zone,
    created_at timestamp without time zone NOT NULL,
    deadline timestamp without time zone,
    description character varying(500),
    name character varying(255) NOT NULL,
    reason character varying(500),
    task_state_id bigint NOT NULL
);

CREATE TABLE tasks.tasks_categories (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);

ALTER TABLE tasks.tasks_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tasks.tasks_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE tasks.tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tasks.tasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE tasks.tasks_members (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    member_code bigint NOT NULL,
    task_id bigint NOT NULL
);

ALTER TABLE tasks.tasks_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tasks.tasks_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE tasks.tasks_metadata (
    id bigint NOT NULL,
    key character varying(255) NOT NULL,
    task_id bigint NOT NULL
);

ALTER TABLE tasks.tasks_metadata ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tasks.tasks_metadata_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE tasks.tasks_metadata_properties (
    id bigint NOT NULL,
    key character varying(255) NOT NULL,
    value character varying(255) NOT NULL,
    metadata_id bigint NOT NULL
);

ALTER TABLE tasks.tasks_metadata_properties ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tasks.tasks_metadata_properties_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE tasks.tasks_states (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);

ALTER TABLE tasks.tasks_states ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tasks.tasks_states_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE tasks.tasks_steps (
    id bigint NOT NULL,
    code character varying(20) NOT NULL,
    description character varying(1000) NOT NULL,
    status boolean NOT NULL,
    step_id bigint,
    task_id bigint NOT NULL,
    task_type_step_id bigint NOT NULL
);

ALTER TABLE tasks.tasks_steps ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tasks.tasks_steps_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE tasks.tasks_types_steps (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);

ALTER TABLE tasks.tasks_types_steps ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tasks.tasks_types_steps_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE tasks.tasks_x_categories (
    task_id bigint NOT NULL,
    category_id bigint NOT NULL
);

INSERT INTO tasks.tasks_categories VALUES (1, 'INTEGRACIÓN DE INSUMOS');
INSERT INTO tasks.tasks_categories VALUES (2, 'GENERACIÓN INSUMO CATASTRAL');
INSERT INTO tasks.tasks_categories VALUES (3, 'CONTROL DE CALIDAD XTF');

INSERT INTO tasks.tasks_states VALUES (1, 'ASIGNADA');
INSERT INTO tasks.tasks_states VALUES (2, 'CERRADA');
INSERT INTO tasks.tasks_states VALUES (3, 'CANCELADA');
INSERT INTO tasks.tasks_states VALUES (4, 'INICIADA');

INSERT INTO tasks.tasks_types_steps VALUES (1, 'ÚNICA VEZ');
INSERT INTO tasks.tasks_types_steps VALUES (2, 'SIEMPRE');

SELECT pg_catalog.setval('tasks.tasks_categories_id_seq', 3, true);
SELECT pg_catalog.setval('tasks.tasks_id_seq', 1, false);
SELECT pg_catalog.setval('tasks.tasks_members_id_seq', 1, false);
SELECT pg_catalog.setval('tasks.tasks_metadata_id_seq', 1, false);
SELECT pg_catalog.setval('tasks.tasks_metadata_properties_id_seq', 1, false);
SELECT pg_catalog.setval('tasks.tasks_states_id_seq', 4, true);
SELECT pg_catalog.setval('tasks.tasks_steps_id_seq', 1, false);
SELECT pg_catalog.setval('tasks.tasks_types_steps_id_seq', 2, true);

ALTER TABLE ONLY tasks.tasks_categories
    ADD CONSTRAINT tasks_categories_pkey PRIMARY KEY (id);

ALTER TABLE ONLY tasks.tasks_members
    ADD CONSTRAINT tasks_members_pkey PRIMARY KEY (id);

ALTER TABLE ONLY tasks.tasks_metadata
    ADD CONSTRAINT tasks_metadata_pkey PRIMARY KEY (id);

ALTER TABLE ONLY tasks.tasks_metadata_properties
    ADD CONSTRAINT tasks_metadata_properties_pkey PRIMARY KEY (id);

ALTER TABLE ONLY tasks.tasks
    ADD CONSTRAINT tasks_pkey PRIMARY KEY (id);

ALTER TABLE ONLY tasks.tasks_states
    ADD CONSTRAINT tasks_states_pkey PRIMARY KEY (id);

ALTER TABLE ONLY tasks.tasks_steps
    ADD CONSTRAINT tasks_steps_pkey PRIMARY KEY (id);

ALTER TABLE ONLY tasks.tasks_types_steps
    ADD CONSTRAINT tasks_types_steps_pkey PRIMARY KEY (id);

ALTER TABLE ONLY tasks.tasks_members
    ADD CONSTRAINT fk2ffgbngedy5k8g9jphuemkx0i FOREIGN KEY (task_id) REFERENCES tasks.tasks(id);

ALTER TABLE ONLY tasks.tasks_steps
    ADD CONSTRAINT fk91eqoe255e72lsmpkxo6psvmx FOREIGN KEY (task_id) REFERENCES tasks.tasks(id);

ALTER TABLE ONLY tasks.tasks_x_categories
    ADD CONSTRAINT fkb4cb0gqnvfbf5ocarsrl06pub FOREIGN KEY (category_id) REFERENCES tasks.tasks_categories(id);

ALTER TABLE ONLY tasks.tasks_metadata
    ADD CONSTRAINT fki3ykfnubwe9x93mtfvbg1sdko FOREIGN KEY (task_id) REFERENCES tasks.tasks(id);

ALTER TABLE ONLY tasks.tasks_steps
    ADD CONSTRAINT fkmh1uts5s7p5i78ya704i9dvx3 FOREIGN KEY (task_type_step_id) REFERENCES tasks.tasks_types_steps(id);

ALTER TABLE ONLY tasks.tasks_steps
    ADD CONSTRAINT fkmn0ex8gysk22vtt0anfy271jw FOREIGN KEY (step_id) REFERENCES tasks.tasks_steps(id);

ALTER TABLE ONLY tasks.tasks_metadata_properties
    ADD CONSTRAINT fkn41ds9u9mdvobrd8sxiw9as6p FOREIGN KEY (metadata_id) REFERENCES tasks.tasks_metadata(id);

ALTER TABLE ONLY tasks.tasks
    ADD CONSTRAINT fkpw2opc7ay9q1wua1kkbmwg7qc FOREIGN KEY (task_state_id) REFERENCES tasks.tasks_states(id);

ALTER TABLE ONLY tasks.tasks_x_categories
    ADD CONSTRAINT fkrltxlgup2ma7fp2jxy26gpqvs FOREIGN KEY (task_id) REFERENCES tasks.tasks(id);